<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>control_brazo</name>
  <version>0.0.0</version>
  <description>Nodo de control de cinemática y trayectorias</description>
  <maintainer email="agustin@todo.todo">agustin</maintainer>
  <license>TODO: License declaration</license>

  <!-- Añade estas dependencias si aún no las tienes -->
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- OBLIGATORIO: Esta es la línea que resuelve el error -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
